// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://livxtofrtyeriqfkjmtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpdnh0b2ZydHllcmlxZmtqbXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDI1MTEsImV4cCI6MjA3MjkxODUxMX0.-79Bs3d7bfEj0YiCFsSf8XGzIYt9pxkrYqtyE6PqNBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});